name: Build 

on: 

  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create dist folder
        run: mkdir -p dist
      - name: Get the OS architecture
        id: get_arch
        run: echo "ARCH=x86_$(getconf LONG_BIT)" >> $GITHUB_ENV
      - name: Get the version number
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
      - name: Build src/main.cpp 
        run: g++ src/main.cpp -o dist/main
      - name: Tar the release
        run: | 
          tar -czvf dist/main-${{ env.VERSION }}-${{ env.ARCH }}.tar.gz dist/main
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "noreply@github.com"
      - name: Create the release
        run: |
          gh release create ${{ env.VERSION }} ./dist/*.tar.gz --generate-notes 